### ISSUE TITLE
Research data necessary for merchant/consumer interface

### ISSUE THREAD

**Issue by MarkVincentGo** [ReactWare/EatLadleApp#3]
so that we can add content to the app, enter here what would be the data we could add to the database

**Comment by MarkVincentGo** [comment]
Name
Name of Restaurant
Address

**Comment by KN408** [comment]
Hours
Phone number
Type of restaurant (Japanese, Mexican, Vietnamese... etc.)

Menu Items:
Name 
Photos?
Allergies
Category (Entree/Side/Drink/Other)

**Comment by gabsong** [comment]
@MarkVincentGo @KN408 could you also add the data types for each?

**Comment by gabsong** [comment]
@KN408 I think for things like **type of restaurant** we can add them on the go if it's hard to come up with the entire collection.

**Comment by KN408** [comment]
**_Restaurant Data:_**
-----
**Name** - String
**Category** - (Give a list of strings to pick from?) 
**Hours**: 
- We can either use strings for the days or use numbers (1-7) representing the day of the week
- For hours, I like how yelp used 24 hour time in string format, makes data a little easier so you don't have to worry about AM/PM ( "open": "0800", "close": "2200" for example) 
**Phone Number:**
Yelp also has a good system where they have two forms of data for this. Might be extra for our use case though so we can just pick one.
phoneNumber - string "+1 (123) 456-7890"
displayPhone - string "(123) 456-7890"
**Location:**
Address - string
City - string 
zipcode - string
state - string
country - string (maybe don't need a country?)
-----
**_Menu Items:_**
-----
**Name** - String
**Category** - (Entree/Side/Drink/Other. pick from a list of strings?)
**Allergies** - I was planning on giving a list of set allergies they can toggle true/false for, so booleans for these unless you guys have a better approach
**Description** - string
**Pictures**? - Could be URLs or we can upload fake data pics for now??
